version: "3.7"
services:
  app:
    build:
      args:
        user: frtzdv
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: backend-knowledge-test
    container_name: coding-test
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: coding_test
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.23
    container_name: backend-knowledge-test-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - net

  frontend:
    build:
      context: ../coding-test-frontend
      dockerfile: Dockerfile
    image: frontend-knowledge-test
    container_name: coding-test-frontend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../coding-test-frontend:/var/www
    networks:
      - net
    ports:
      - "3000:3000"

networks:
  net:
    driver: bridge
